######################################################################################
### Admin
######################################################################################

### admin login
POST http://localhost/admin/login HTTP/1.1
Content-Type: application/json

{
    "adminUserId" : "admin",
    "password" : 1111
}

### admin logout
POST http://localhost/admin/logout HTTP/1.1
Content-Type: application/json

admin

######################################################################################
### User
######################################################################################

### user login
POST http://localhost/user/login HTTP/1.1
Content-Type: application/json

{
    "userId" : "test@test.com",
    "apiKey" : "qkwej12i39lwqe",
    "userLevel" : 0
}

### user logout
POST http://localhost/user/logout HTTP/1.1
Content-Type: application/json

{
    "userId" : "test@test.com"
}

### get user
GET http://localhost/user/test@test.com HTTP/1.1

######################################################################################
### Company
######################################################################################

### insert preComapnyList
POST http://localhost/preCompanyList HTTP/1.1
Content-Type: application/json

[
    {"userId":"hairstargram@outlook.com","regionNo":"0","companyName":"참헤어","companyAddress":"용산점"},
    {"userId":"hairstargram@outlook.com","regionNo":"1","companyName":"참헤어","companyAddress":"부현점"},
    {"userId":"hairstargram@outlook.com","regionNo":"2","companyName":"참헤어","companyAddress":"해운대점"}
]

### insert preComapny
POST http://localhost/preCompany HTTP/1.1
Content-Type: application/json

{
    "userId":"hairstargram@outlook.com",
    "regionNo":"2",
    "companyName":"참헤어",
    "companyAddress":"용산점"
}

### get preCompanyList
GET http://localhost/preCompanyList/hairstargram@outlook.com HTTP/1.1


### delete preCompanyNo
DELETE http://localhost/preCompany/1 HTTP/1.1

######################################################################################
### File
######################################################################################

### get FileInfo
GET http://localhost/file/1 HTTP/1.1