######################################################################################
### Admin
######################################################################################

### admin login
POST http://localhost/admin/login HTTP/1.1
Content-Type: application/json

{
    "adminUserId" : "admin",
    "password" : 1111
}

### admin logout
POST http://localhost/admin/logout HTTP/1.1
Content-Type: application/json

admin

######################################################################################
### User
######################################################################################

### user login
POST http://localhost/user/login HTTP/1.1
Content-Type: application/json

{
    "userId" : "test@test.com",
    "apiKey" : "qkwej12i39lwqe",
    "userLevel" : 0
}

### user logout
POST http://localhost/user/logout HTTP/1.1
Content-Type: application/json

{
    "userId" : "test@test.com"
}

### get user
GET http://localhost/user/test@test.com HTTP/1.1

######################################################################################
### Company
######################################################################################

### insert preComapny
POST http://localhost/preCompany HTTP/1.1
Content-Type: application/json

[
    {"regionNo":"0","companyName":"참헤어","companyAddress":"용산점"},
    {"regionNo":"1","companyName":"참헤어","companyAddress":"부현점"},
    {"regionNo":"2","companyName":"참헤어","companyAddress":"해운대점"}
]